/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://xuycktni6bhvrmltv3lrps2kzy.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-go7xjky5tbb5jnrng4igz6bajy",
    "aws_cognito_identity_pool_id": "eu-west-1:32c317c7-3d74-4e20-b0e4-c250bbdec22b",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_VsuAzFclE",
    "aws_user_pools_web_client_id": "301ecseman2p1pha9iv7bp4cnr",
    "oauth": {
        "domain": "inergy-auth-sandpit.auth.eu-west-1.amazoncognito.com"
    },
    "aws_user_files_s3_bucket": "b2c02f8950156b34fbdadcc581baf54c3c0172036-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
